### ISSUE TITLE
Transfer the concept functions into the R package

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/sensingcluesr#1]
follow up on ticket [#133](https://github.com/SensingClues/wildcat-api-r/issues/133)

- get_groups()
- get_observations()
- get_concept_counts()

**Comment by Mell-A** [comment]
@hugokoopmans @dkd58 can you test the functions in the description? You can load the package with `devtools::install_github('sensingclues/wildcatr')`

**Comment by dkd58** [comment]
Als ik eerst even:
```
`library(httr)

SC_URL <- "https://focus.sensingclues.org/" # Sensing Clues Focus

login_cluey <- function( ...etc ...)`

```
definieer en vervolgens inlog,

krijg ik:

- met `get_groups(cookie)` precies dezelfde groepen als in WildCat ObservationReport met date range "heel lang" 
- met `get_observations(cookie, group = 'focus-project-7136973', from = Sys.Date()-30, to = Sys.Date())` een dataframe met 22 rijen, terwijl ik in WildCat ObSRep Raw Observations 8 rijen (met daarin 13 concepten) krijg. Als ik alle hogere nivo's meetel, inclusief de root, dan kom ik wel precies op 22.
- met `get_concept_counts(cookie, group = 'focus-project-7136973', from = Sys.Date()-30, to = Sys.Date())` een list met lengte 21 (zonder de root??)

Helpt dat wat?

**Comment by Mell-A** [comment]
@dkd58 voor de meest robuuste vergelijking kun je de functies in de console runnen ipv in wildcat, ik zie dan geen verschillen tussen wildcatr::get_observations() en get_observations() uit de library. Overigens hoef je SC_URL niet te definieren of library httr niet aan te roepen, dat zit al in de package, zie ook de documentatie.
