### ISSUE TITLE
Transfer the ontology functions into the R-package

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/sensingcluesr#2]
follow up on ticket [#133](https://github.com/SensingClues/wildcat-api-r/issues/133)

- get_hierarchy()
- get_id()
- get_label()
- get_parent_id()
- get_parent_label()
- get_children_id()
- get_children_label()

**Comment by Mell-A** [comment]
@hugokoopmans @dkd58 can you test all the functions related to ontologies?
