### ISSUE TITLE
Make GetObs more robust (for zero concept case)

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/sensingcluesr#25]
we tried to ensure that all obs have concepts, but somehow obs are created which have 0 concepts related.
To ensure that not everything brakes when obs like these are in reports, we will create a solution in the package that will ensure that these obs are ignored

this is a pre-requisite for Bas to continue with the chili fence report, as the issue pops up there

**Comment by Mell-A** [comment]
succesfully tested the code suggested by Bas on the following requests where there is at least one observation without concepts

`get_observations(cookie, "focus-project-5203273", from = '2024-03-01', to = '2024-03-30')`  (Human Wildlife Coexistence)

`get_observations(cookie, "focus-project-8950", from = '2022-06-01', to = '2023-01-01')` (WildlifeWorks01 Upload)
