### ISSUE TITLE
Separate function for getting attributes of observations instead of in get_observations()

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/sensingcluesr#5]
generically unpack the attributes, so the same functionality can be used in get_tracks()

**Comment by Mell-A** [comment]
added function unpack_attributes() and implemented it in get_observations() and get_tracks(), this affects all the reports (in maps the attributes are unused) and can be tested via https://github.com/SensingClues/patrol-report/issues/6 , https://github.com/SensingClues/observation-report/issues/5 and https://github.com/SensingClues/community-report/issues/6

**Comment by MennoValkenburg** [comment]
@JanKeesSchakel, can you please test the three reports mentioned above and the way the observations are retrieved?

**Comment by JudithDekkers** [comment]
tested CW and this report works fine!

**Comment by JanKeesSchakel** [comment]
Tested and satisfied :-) 

CW
Observations report
Obs map
Patrol report
Patrol map
