### ISSUE TITLE
Update pageLength optimal value for data retrieval performance

### ISSUE THREAD

**Issue by JudithDekkers** [SensingClues/sensingcluesr#6]
for track metadata and observation data (50/page), for track coordinates this is already implemented (500/page), also investigate higher numbers 1000/page etc.

**Comment by Mell-A** [comment]
see the wildcat channel on Slack for the different scenarios that were tested, I suggest to change the page length to 500/page in get_tracks() and get_observations(), similar as in get_track_coordinates()

**Comment by Mell-A** [comment]
please compare the processing time between the test and production versions of the applications @JudithDekkers

**Comment by JudithDekkers** [comment]
the page length did not increase the speed.
this ticket will be closed and follow up actions are here: https://github.com/SensingClues/sccss-platform-documentation/issues/490
